# Flags
show_drafts: false

# Site configuration
url: https://emozley.com
permalink: /blog/:year/:month/:title/
timezone: Europe/London

# Technical configuration
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
